// const BASE = 'http://localhost:5000'
const BASE = 'https://park-and-dragon.herokuapp.com'

export const GET_TASKS_URL = BASE + '/alltasks?user_id=1'
export const GET_SHOP_ITEMS_URL = BASE + '/getshopitem?user=1'
export const BUY_SHOP_ITEMS_URL = BASE + '/getinventory?user=1'
export const GET_INVENTORY_URL = BASE + '/getinventory?user=1'
export const LOGIN_URL = BASE + '/login'
export const LOGOUT_URL = BASE + '/logout'
export const PROTECTED_URL = BASE + '/protected'
export const GET_USER_URL = BASE + '/user'
export const CODE_VERIFICATION_URL = BASE + '/applycode'
